name: Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  build-and-distribute:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Set up Java 17 for Android build
      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version

      # Set up the Keystore file by decoding from the secret
      - name: Set up Keystore file
        run: |
          echo $ANDROID_KEYSTORE | base64 --decode > android/app/my-upload-key.keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}

      # Build the Android APK
      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew  # Ensure gradlew has execute permissions
          ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_ALIAS_PASSWORD }}

      # Upload the APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}